apiVersion: v1
kind: Service
metadata:
  name: sentinel-datetime
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: datetime
    context: sentinel-services
    version: v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentinel-datetime
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: datetime
        context: sentinel-services
        version: v1
    spec:
      containers:
        -
          name: sentinel-datetime
          image: docker.steventaylor.me/sentinel-datetime-x86_64:latest
          imagePullPolicy: Always
          env:
            -
              name: "PORT"
              value: "5000"
            -
              name: "CONSUL"
              value: "consul.steventaylor.me"
            -
              name: "redis"
              value: "redis-redis"
          ports:
            -
              containerPort: 5000
              protocol: TCP
      nodeSelector:
          beta.kubernetes.io/arch: amd64